name: Automated API tests using Postman CLI
on: 
    push:
        branches: [ main, master ]
    pull_request:
        branches: [ main, master ]
    workflow_dispatch:
        
jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "43856419-b3affee4-8d55-4033-bd5a-47bbda2077be" -e "43856419-0c62d422-febc-445b-b2d1-de5c2d712343"